import fs from "fs";
import PDFDocument from "pdfkit";
import ExcelJS from "exceljs";

/**
 * Streams a class result sheet to PDF: school header (+ logo if a local
 * file path is configured via SCHOOL_LOGO_PATH), exam metadata, the full
 * marks table, and a footer with generation info. A4, print-friendly.
 *
 * @param {Object} meta - { class, section, subject, examType, examDate }
 * @param {Array}  rows - [{ rollNumber, studentId, name, fatherName, marksObtained, totalMarks, percentage, grade, isAbsent }]
 * @param {String} generatedByName
 */
export const exportMarksPDF = (res, meta, rows, generatedByName) => {
  const doc = new PDFDocument({ margin: 40, size: "A4" });

  res.setHeader("Content-Type", "application/pdf");
  res.setHeader(
    "Content-Disposition",
    `attachment; filename=result-${meta.class}-${meta.section}-${meta.subject}.pdf`
  );
  doc.pipe(res);

  // ---- Header: school name + optional logo ----
  const schoolName = process.env.SCHOOL_NAME || "Student Management System";
  const logoPath = process.env.SCHOOL_LOGO_PATH;
  let textX = 40;

  if (logoPath && fs.existsSync(logoPath)) {
    try {
      doc.image(logoPath, 40, 35, { width: 50, height: 50 });
      textX = 100;
    } catch {
      // If the file exists but isn't a valid image, just skip it silently
      // rather than crashing the whole export.
    }
  }

  doc.fontSize(16).font("Helvetica-Bold").text(schoolName, textX, 40);
  doc.fontSize(11).font("Helvetica").text(`${meta.examType} — Result Sheet`, textX, 62);
  doc.moveDown(2);

  // ---- Exam metadata ----
  doc.fontSize(9).font("Helvetica");
  const metaLine = `Class: ${meta.class}-${meta.section}   |   Subject: ${meta.subject}   |   Exam: ${meta.examType}   |   Date: ${
    meta.examDate ? new Date(meta.examDate).toLocaleDateString() : "-"
  }`;
  doc.text(metaLine, { align: "left" });
  doc.moveDown(1);

  // ---- Table ----
  const columns = [
    { key: "rollNumber", label: "Roll No", width: 55 },
    { key: "name", label: "Student Name", width: 130 },
    { key: "fatherName", label: "Father Name", width: 120 },
    { key: "marks", label: "Marks", width: 70 },
    { key: "percentage", label: "%", width: 50 },
    { key: "grade", label: "Grade", width: 50 },
    { key: "status", label: "Status", width: 55 },
  ];

  let y = doc.y + 5;
  const startX = 40;
  const rowHeight = 20;

  const drawRow = (row, isHeader = false) => {
    let x = startX;
    doc.font(isHeader ? "Helvetica-Bold" : "Helvetica").fontSize(9);
    columns.forEach((col) => {
      doc.text(String(row[col.key] ?? ""), x, y, { width: col.width, ellipsis: true });
      x += col.width;
    });
    y += rowHeight;
  };

  const headerRow = columns.reduce((acc, col) => ({ ...acc, [col.key]: col.label }), {});
  drawRow(headerRow, true);
  doc.moveTo(startX, y).lineTo(startX + columns.reduce((s, c) => s + c.width, 0), y).stroke();
  y += 4;

  rows.forEach((row) => {
    if (y > doc.page.height - 80) {
      doc.addPage();
      y = 50;
    }
    drawRow({
      rollNumber: row.rollNumber,
      name: row.name,
      fatherName: row.fatherName || "-",
      marks: row.isAbsent ? "Absent" : `${row.marksObtained}/${row.totalMarks}`,
      percentage: row.isAbsent ? "-" : `${row.percentage}%`,
      grade: row.isAbsent ? "-" : row.grade,
      status: row.isAbsent ? "Absent" : row.grade === "F" ? "Fail" : "Pass",
    });
  });

  // ---- Footer ----
  const footerY = doc.page.height - 50;
  doc
    .fontSize(8)
    .font("Helvetica")
    .text(`Generated on ${new Date().toLocaleString()}`, startX, footerY, { align: "left" })
    .text(`Generated by: ${generatedByName || "Admin"}`, startX, footerY + 12, { align: "left" });

  doc.end();
};

/**
 * Streams a class result sheet to Excel (.xlsx).
 */
export const exportMarksExcel = async (res, meta, rows, generatedByName) => {
  const workbook = new ExcelJS.Workbook();
  workbook.creator = process.env.SCHOOL_NAME || "Student Management System";
  const sheet = workbook.addWorksheet("Result");

  // Title rows above the table
  sheet.mergeCells("A1:G1");
  sheet.getCell("A1").value = `${process.env.SCHOOL_NAME || "Student Management System"} — ${meta.examType} Result`;
  sheet.getCell("A1").font = { bold: true, size: 14 };

  sheet.mergeCells("A2:G2");
  sheet.getCell("A2").value = `Class: ${meta.class}-${meta.section}  |  Subject: ${meta.subject}  |  Date: ${
    meta.examDate ? new Date(meta.examDate).toLocaleDateString() : "-"
  }`;
  sheet.getCell("A2").font = { italic: true, size: 10 };

  sheet.addRow([]); // spacer row

  // NOTE: deliberately NOT using `sheet.columns = [...]` with header/key
  // metadata here — ExcelJS auto-writes those headers into row 1 as a
  // side effect of that setter, which would silently overwrite the title
  // row above. Setting widths directly and building rows as plain arrays
  // avoids that trap.
  sheet.getColumn(1).width = 12; // Roll No
  sheet.getColumn(2).width = 18; // Admission No
  sheet.getColumn(3).width = 25; // Student Name
  sheet.getColumn(4).width = 22; // Father Name
  sheet.getColumn(5).width = 14; // Marks
  sheet.getColumn(6).width = 14; // Percentage
  sheet.getColumn(7).width = 10; // Grade
  sheet.getColumn(8).width = 10; // Status

  const headerRow = sheet.addRow([
    "Roll No",
    "Admission No",
    "Student Name",
    "Father Name",
    "Marks",
    "Percentage",
    "Grade",
    "Status",
  ]);
  headerRow.font = { bold: true };
  headerRow.fill = { type: "pattern", pattern: "solid", fgColor: { argb: "FFE0E7FF" } };

  rows.forEach((row) => {
    sheet.addRow([
      row.rollNumber,
      row.studentId,
      row.name,
      row.fatherName || "-",
      row.isAbsent ? "Absent" : `${row.marksObtained}/${row.totalMarks}`,
      row.isAbsent ? "-" : `${row.percentage}%`,
      row.isAbsent ? "-" : row.grade,
      row.isAbsent ? "Absent" : row.grade === "F" ? "Fail" : "Pass",
    ]);
  });

  sheet.addRow([]);
  sheet.addRow([`Generated on ${new Date().toLocaleString()} by ${generatedByName || "Admin"}`]);

  res.setHeader(
    "Content-Type",
    "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
  );
  res.setHeader(
    "Content-Disposition",
    `attachment; filename=result-${meta.class}-${meta.section}-${meta.subject}.xlsx`
  );

  await workbook.xlsx.write(res);
  res.end();
};